### PR TITLE
Fix a few typos, grammar in docs

### PR DESCRIPTION
**Pull request by zephsinx**
A quick pass over some of the docs to fix:

1. Typos: Common misspellings, missed/extra letters, etc.
2. Grammar: Extra/missing hyphens, its vs. it's, set up vs. setup, etc.

Only covers some of the files so far. If this PR is helpful I might run through the remaining files as well. Happy to update or change any of the suggestions if needed.

### CODE REVIEW

**Comment by Ik1497** [comment]
Thanks for the fixes! I will look at the PR ASAP

**Review by Whipstickgostop — COMMENTED** [review]
Grammar & typo fixes look great!

The markdown tables are a remnant from the Wiki migration and we're currently in progress of moving all/most of them into frontmatter properties. A lot of those may end up causing conflicts with current work but I'll let @Ik1497 comment to that.

Thanks a ton for going through all these files and taking a look <3

**Comment by zephsinx** [comment]
@Whipstickgostop that makes sense! I'll go through and revert those changes to make it easier

**Comment by zephsinx** [comment]
Alright I think I reverted all the table changes!

**Review by Whipstickgostop — APPROVED** [review]

**Comment by Whipstickgostop** [comment]
tyvm! Your contribution is very much appreciated

**Pull request merged**
